Update README with spelling fix in command
Blue-Dog-Archolite/ansible-workstations-ubuntu pull request #4
Opened 2020-12-09 21:36 UTC by janemiceli

2021-01-07 16:19 UTC, Blue-Dog-Archolite requested changes

2021-01-07 16:19 UTC, Blue-Dog-Archolite commented on roles/gui/tasks/log.yml
> +---
Remove Debug

2021-01-07 16:19 UTC, Blue-Dog-Archolite commented on roles/post-brew/tasks/pipfiles/vim3/Pipfile
> +python_version = "4.1"
This version does not exist.

2021-01-07 16:19 UTC, Blue-Dog-Archolite commented on roles/post-brew/tasks/vim-pip-installs.yml
> +    python3 -m pipenv --two
Whitespace

2021-01-07 16:19 UTC, Blue-Dog-Archolite commented on roles/pre-install/tasks/apt-install.yml
> +  #when: ansible_virtualization_type != "xen"
Remove commented lines.

2021-01-07 16:19 UTC, Blue-Dog-Archolite commented on roles/pre-install/tasks/directory-prep.yml
> +#- name: Create home directory for tools
Is this required? Docs suggest this is an expected function.

2021-01-07 16:19 UTC, Blue-Dog-Archolite commented on roles/workstation/tasks/apt-install.yml
> +      - net-tools
Sort the dependencies so reading and location of packages is easier.

2021-01-07 16:19 UTC, Blue-Dog-Archolite commented on roles/workstation/tasks/apt-repos.yml
> +  when: ansible_virtualization_type != "xen"
move this check up to the workstation main level and not at the task level. dry and all that.

2021-01-13 02:54 UTC, janemiceli commented
I hate the team update based on the comments here. I expect all the changes requested are in his and we can close this one without mergning.

2021-01-13 02:54 UTC, closed without merging